fix: remove unnecessary backticks
ES-Community/Code-of-conduct pull request #102
Opened 2020-11-02 16:26 UTC by Mesteery

2020-11-03 20:49 UTC, fraxken commented
Je ne suis pas certains que la PR soi très pertinente. De plus je pense que les backticks sont pour faire comme en `markdown`. (Pour coller avec le README plus bas).

2020-11-03 21:34 UTC, Mesteery commented
C'est juste parce que ```console.log(`- `#${name}` - ${description}`)``` n'est pas valide.

2020-11-28 21:16 UTC, Aakodal requested changes

2020-11-28 21:16 UTC, Aakodal commented on README.md
> +    console.log(`- #${name} - ${description}`)
Au lieu de les retirer complètement, tu peux simplement les échapper
```suggestion
    console.log(`- \`#${name}\` - ${description}`)
```

2020-11-28 21:28 UTC, Mesteery commented on README.md
> +    console.log(`- #${name} - ${description}`)
Je pensais pas que c'était volontaire.

2020-11-28 21:35 UTC, Aakodal approved these changes

2020-12-19 22:45 UTC, targos approved these changes

2020-12-19 22:46 UTC, fraxken approved these changes

2020-12-19 22:56 UTC, RomainLanz approved these changes

2020-12-21 15:13 UTC, CyriacBr approved these changes

2020-12-21 15:27 UTC, Xstoudi approved these changes

2020-12-22 17:55 UTC, Purexo approved these changes

2021-01-11 16:06 UTC, merged