Ajout du canal #live
ES-Community/Code-of-conduct pull request #106
Opened 2021-12-30 19:22 UTC by RomainLanz

Hello ! 👋🏻 

Je propose d'ajouter le canal #live dans notre Discord.

Celui-ci permettrai d'annoncer des lives futures ou en cours de nos membres.
À voir si on autorise à pub un live qui ne concerne pas le développement.

Le concept est de garder le canal propre.
C'est-à-dire qu'on peut poster pour annoncer un live futur, ou le fait d'être en live, mais une fois celui-ci passé, il faut supprimer le message d'annonce (ou de live).

C'est comme cela que le canal fonctionne sur le Discord de Grafikart, et je pense que c'est une bonne méthode.

![image](https://user-images.githubusercontent.com/2793951/147782088-9514f20f-236c-4267-a4be-50f8d9e97264.png)

2021-12-30 19:34 UTC, fraxken approved these changes
Ok pour moi.

2021-12-30 19:34 UTC, targos approved these changes
On pourrait programmer le bot pour gérer les messages

2021-12-30 19:34 UTC, RomainLanz commented
> On pourrait programmer le bot pour gérer les messages

Comment tu comptes faire ça ?

2021-12-30 19:38 UTC, targos commented
On peut imaginer plusieurs choses... Commandes pour automatiser une partie du message, interdire un message qui n'a pas d'URL, supprimer les messages après un certain temps en cas d'oubli...

2021-12-30 19:41 UTC, RomainLanz commented
Sauf que justement, le message sera très abstrait et personnel à celui qui le poste, on n'est pas obligé de respecter un format, comme de mettre un lien (si on annonce un stream qui est dans plusieurs heures par exemple), on posterait le lien une fois le live lancer.

La seul chose que je peux voir utile, c'est de supprimer un message après un certain temps (24h?). A mon avis, ça reste overkill et du travail inutile. Il suffit qu'un admin regarde le canal pour le nettoyer si jamais il y a besoin de le faire.

2021-12-30 20:26 UTC, Mesteery commented on README.md
> +- `#live` - Salon d'annonce de stream de nos membres (en rapport avec la programation, ou pas !)
```suggestion
- `#live` - Salon d'annonce de stream de nos membres (en rapport avec la programmation, ou pas !)
```
Ou 
```suggestion
- `#live` - Salon d'annonce de stream de nos membres
```

2021-12-30 20:46 UTC, Xstoudi commented
Pour moi on peut laisser les deux possibilités ouvertes :
- soit la personne peut poser un message avec le lien de son stream et le supprime à la fin ;
- soit la personne ajoute sa chaîne à la liste des chaînes trackées par le bot et le bot envoie/supprime automatiquement le message d'annonce. 

De cette manière la propal peut déjà s'appliquer avant que quelqu'un ne se chauffe à ajouter la feature sur le bot et la personne peut éventuellement personnaliser son message de stream.

2021-12-30 20:53 UTC, RomainLanz commented
À mon avis, c'est une fonctionnalité inutile qui va prendre du temps à faire (d'autant plus que Twitch n'est pas la seule plateforme de streaming qui existe), mais je ne vois pas de raison de l'empêcher si quelqu'un a envie de la coder.

2021-12-30 20:56 UTC, Xstoudi approved these changes

2022-01-06 09:43 UTC, Purexo requested changes
Ok, mais faut rajouter un minimum de règle, comme préciser 
- date et heure du stream
- l'objet du stream
- limiter les stream au contenu pertinent de ce discord (du dev, et pas du JV par exemple)
- pas de ping

Après ok pour la mise en forme libre.

Et @RomainLanz ok va pas ce le cacher, c'est surtout pour toi ce canal xD

2022-01-06 09:48 UTC, CyriacBr commented
> Et @RomainLanz ok va pas ce le cacher, c'est surtout pour toi ce canal xD
Peut-être que ça donnera envie à d'autres de partager ou de se lancer.

Ok pour moi, un canal dédié c'est bien pour l'organisation.

2022-01-06 09:48 UTC, CyriacBr approved these changes

2022-01-06 09:55 UTC, RomainLanz commented
> Ok, mais faut rajouter un minimum de règle, comme préciser
> 
>     * date et heure du stream
> 
>     * l'objet du stream
> 
>     * limiter les stream au contenu pertinent de ce discord (du dev, et pas du JV par exemple)
> 
>     * pas de ping
> 
> 

Je serais dans l'avis de laisser libre pour le moment, et s'il le faut, cadrer.
Ça sert à rien de cadrer en amont, surtout qu'on n'imagine pas toutes les uses-cases. Il suffit de voir le bot dans `#liens`, même avec des années de use-case et data, il est trop stricte.

> Et @RomainLanz ok va pas ce le cacher, c'est surtout pour toi ce canal xD

Yes ! Comme le dit @CyriacBr, ça peut motiver d'autre à le faire aussi, le but, c'est surtout d'éviter de spam un canal comme `#blabla` pour ce genre de chose.

2022-01-06 21:54 UTC, Purexo commented
> Ça sert à rien de cadrer en amont, surtout qu'on n'imagine pas toutes les uses-cases. Il suffit de voir le bot dans #liens, même avec des années de use-case et data, il est trop stricte.

C'est bien pour ça que la mise en forme doit rester libre. Mais je ne vois pas l'intérêt d'annoncer un live sans ces info. Ça me semble être un minimum.

Concernant le sujet du live, on est une communauté centré sur le dev, plus particulièrement ECMAScript, ok pour que des gens fassent leur promo, mais sur des sujets susceptible d'intéresser la communauté sinon c'est pas le lieu je trouve. On n'est pas un discord généraliste.

2022-01-22 15:34 UTC, Purexo approved these changes

2022-01-22 20:15 UTC, merged