docs: add category about the bot
ES-Community/Code-of-conduct pull request #118
Opened 2023-08-13 20:07 UTC by antoineneff

## Changements

- ajout du channel manquant `#advent-of-code`
- ajout d'une catégorie **Bot** avec quelques infos sur ses fonctionnalités ainsi que le lien du repo

Resolves #114

2023-08-25 12:20 UTC, Xstoudi requested changes

2023-08-25 12:20 UTC, Xstoudi commented on README.md
> +Si vous souhaitez l'améliorer ou proposer d'autres fonctionnalités, vous pouvez y contribuer sur [son repos Github](https://github.com/ES-Community/bot).
`repos` devient `dépôt`

2023-08-25 12:21 UTC, Xstoudi commented on README.md
> +Si vous souhaitez l'améliorer ou proposer d'autres fonctionnalités, vous pouvez y contribuer sur [son repos Github](https://github.com/ES-Community/bot).
et `Github` devient `GitHub` :)

2023-08-25 21:00 UTC, Xstoudi approved these changes

2023-08-26 10:12 UTC, fraxken approved these changes

2023-08-26 16:21 UTC, RomainLanz approved these changes

2023-09-06 07:35 UTC, targos approved these changes

2023-09-07 10:16 UTC, merged