Révision du rôle de mentor
ES-Community/Code-of-conduct pull request #96
Opened 2020-07-22 16:24 UTC by Xstoudi

# Introduction
Le concept initial du rôle de mentor est symbolique, mais embarque historiquement un grand nombre de permissions de modération (voir d'administration) pour simplifier le travail de modération. (voir les permissions actuelles tout en bas)

L'idée de cette proposition permet de s'autoriser plus de liberté quant à l'augmentation du nombre de mentors sans prendre le risque de voir certains abus apparaître.

# Modifications du rôle de mentor
## Point de vue utilitaire
Réduire les permissions sensibles touchant à l'administration / modération pour, notamment :
- **Gérer les rôles** : les mentors n'ont pas à créer de nouveaux rôles ou à en modifier / supprimer, uniquement modifier les rôles d'un membre pour accueillir les nouveaux arrivants.
- **Gérer les salons** : les mentors nont pas à créer / modifier / supprimer les salons, ces décisions sont à la discrétion de la communauté et soumises au vote de la communauté.
- **Bannir les membres** : le bannissement est la sanction appropriée dans les cas les plus graves et doit être votée à majorité des mentors, cette sanction ne peut pas découler de la décision personnelle d'un mentor.

Les permissions de couper le micro d'un membre ou de le mettre en sourdine sont à discuter.

## Point de vue symbolique
La description du rôle de mentor a été étoffée dans le code de conduite.

# Administrateurs
Comme vous vous en doutez, les permissions ci-dessus doivent bien partir quelque part. La proposition de cette PR est de créer le rôle d'administrateur. Celui-ci hériterait des permissions perdues par les mentors. Par conséquent, il hériterait aussi de la responsabilité de faire entrer en force les modifications faites au code de conduite par la communauté et de s'assurer que dans le cas d'une décision de bannissement, les mentors aient bien suivi le processus imposé par le code de conduite.
Comme le précisent les modifications au code de conduite, les administrateurs sont nommés à la discrétion des fondateurs parmis les mentors. Ce dernier point est important, les administrateurs ont préalablement été élus mentors par la communauté.

# Permissions actuelles des mentors
![fig1](https://user-images.githubusercontent.com/2575182/88199815-99996c80-cc45-11ea-91a9-4db7f4b7141a.png)
![fig2](https://user-images.githubusercontent.com/2575182/88199869-a7e78880-cc45-11ea-90fd-dede8873b3bb.png)
![fig3](https://user-images.githubusercontent.com/2575182/88199890-af0e9680-cc45-11ea-8064-c8f0d4fe008d.png)

2020-07-22 16:39 UTC, RomainLanz commented
Je suis complètement d'accord avec ta PR, mais du coup je pense qu'il faut revoir la description d'un mentor.

Il est écrit:

> Ils sont responsables de la bonne ambiance sur le Discord, en désamorçant les conflits naissants ou en prenant des sanctions proportionnées

Alors que comme proposé dans cette PR, le but c'est qu'un mentor ne modère pas, appliquer des sanctions c'est justement le rôle d'un modérateur.

A mon avis, un mentor est quelqu'un de compétent dans le domaine, il aime aider les autres et il sait se comporter envers un débutant. Il ne doit pas être un modérateur vu que ce rôle sera pris par les administrateurs.

2020-07-22 17:04 UTC, RomainLanz commented
Pour compléter ma réponse, voici ma proposition de réforme de rôle (ce qui va un peu plus loin que cette PR).

- On garde `Fondateurs`, c'est un rôle honorifique
- On crée un rôle `Administrateurs`, ce rôle est AU-DESSUS de `Fondateurs` au niveau administration
- On crée un rôle `Modérateurs`, ce rôle aidera les `Administrateurs` à modérer, il possède moins de droits que `Administrateurs` (comme le rôle de `Mentors` actuellement)
- On reforme `Mentors`, ces personnes n'auront pas plus de droit qu'un menbre standard

2020-07-22 17:28 UTC, Sebastien-Ahkrin commented
L'idée est bonne, mais vous pensez vraiment qu'il y ai assez de membre pour faire un rôle Modérateurs et un Administrateurs ? 
Surtout que globalement vous êtes tous tout le temps connecté non ?

2020-07-29 20:21 UTC, Purexo commented
Ma philosophie pour les mentor est d'alléger leur rôle de Modération qui est une responsabilité lourde qui ne sied pas à tout le monde.
Mais en leurs laissant des outils pour minimiser les accidents si il y en a.

J'aimerai rappeler qu'a l'origine, l'idée du rôle de Mentor était d’honorer les membres actif - compétent et bienveillant, mais surtout qu'on voulait le moins de hiérarchie possible entre les membres (et c'est bien pour ça que Fondateurs et Mentors ne sont pas séparé dans les liste des membres du rôle Communauté).

D'un coté ça semble logique de vouloir ce simplifier la vie à adopter une hiérarchie de serveur classique (Admin - Modo - Membre + Mentor honorifique), je suis même à l'origine de cette discussion coté fondateur suite à demande de certains Mentor qui ce reconnaitront d'avoir plus de permission pour ce simplifier la vie en cas d'absence des Fondateurs.

J'ai très envie que ça évolue mais en même temps j'ai peur qu'on perde un peu la philosophie "tous égaux" de la communauté.

https://github.com/ES-Community/Code-of-conduct/pull/90

Ce qui me tiens à cœur c'est cette démocratie qu'on essaie de mettre en place et suivre et les membres de la communauté s'y impliquent encore assez peu.

À force d'y réfléchir je pense que l'on devrait :
- faire un rôle d'administration qui est la pour renforcer les rangs des fondateurs parce-que 3 ça commence à devenir juste pour gérer un serveur de cette taille. Dans les faits, les Fondateurs et Mentors susceptible de devenir Admins font déjà le gros de la pars de la modération dont la pars de modération lourde (kick / ban - rappel à l'ordre par MP - gestion de conflit).
- pas de role de Modérateur
- Mentor pour le titre honorifique lié à l'activité - compétence - bienveillance, mais surtout pour dynamiser cette idée de démocratie être force de rappel que tout le monde à sa voix à faire valoir, animer les discussions sur les évolutions du CoC, en proposer de nouvelle, mise en place de weektalks (qui ne sont pas si week que ça :kappa:). Tout en laissant un minimum de permission de Modération car leur investissement et activité dans la communauté peu les rendre prompt à intervenir en cas de dérapage sans avoir besoin de sortir les armes.

2020-08-01 09:08 UTC, Xstoudi commented
Je suis complètement d'accord avec Purexo, par contre j'ai l'impression que c'est exactement ce que propose la PR.

2020-08-01 10:43 UTC, Purexo commented
Faut lire entre les lignes mais oui la PR va dans ce sens je trouve.

Ça manque peut être un peu d'insistance pour la partie animation /démocratie. Et préciser que le rôle de modération par les mentors reste à la marge. Mais l'idée y est.

2020-08-01 12:15 UTC, RomainLanz commented
> Ma philosophie pour les mentor est d'alléger leur rôle de Modération qui est une responsabilité lourde qui ne sied pas à tout le monde.
> J'aimerai rappeler qu'a l'origine, l'idée du rôle de Mentor était d’honorer les membres actif - compétent et bienveillant

Dans ce cas là, autant faire comme défini dans mon message, soit enlever complètement les droits de modération aux Mentors.

> Ce qui me tiens à cœur c'est cette démocratie qu'on essaie de mettre en place et suivre et les membres de la communauté s'y impliquent encore assez peu.

Une hiérarchie de modération n'enlève en rien une communauté démocratique. Je ne vois donc pas vraiment le rapport.

> faire un rôle d'administration qui est la pour renforcer les rangs des fondateurs parce-que 3 ça commence à devenir juste pour gérer un serveur de cette taille

Je ne suis pas fondateur, mais au vu de la taille de la communauté actuellement (soit vraiment petite), je ne pense pas que 3 admins soit limites.

> Mentor pour le titre honorifique lié à l'activité - compétence - bienveillance, [ ... ]. Tout en laissant un minimum de permission de Modération car leur investissement et activité dans la communauté peu les rendre prompt à intervenir en cas de dérapage sans avoir besoin de sortir les armes.

C'est là le problème pour moi et j'y vois de l'incohérence dans vos messages. Soit on enlève le droit de modération aux Mentors, comme ça plusieurs membres pourraient le devenir et ceux qui ne veulent pas modérer peuvent y rester, soit on change pas grand chose (cf la PR), mais du coup il y encore de la modération chez les mentors.

> J'ajouterai que si notre communauté tiens si bien avec si peu de problème, c'est entre autre grâce à cette faible hiérarchie entre les membres et cette égalité affiché.

A mon avis ça n'a strictement aucun rapport, il y a très peu de membre actif dans notre communauté, elle se tient bien pour cette raison, le fait qu'il y ait une faible hiérarchie n'a aucun rapport avec cela.

2020-08-01 13:11 UTC, Purexo commented
Le but n'est pas nécessairement de supprimer totalement les permissions de Mentor mais de les réduire.
Et c'est pas parce-que un Mentor à des permissions de Modération (qui seront assez minime au final) qu'un Mentor doit faire de la Modération.

2020-08-01 13:58 UTC, fraxken commented
En ce qui me concerne je doute qu'il soi spécifiquement nécessaire d'avoir un double rôle Administrateurs/Modérateurs (un seul suffit sachant qu'on n'est pas 50^^).

- Je n'ai rien contre l'idée d'avoir un rôle Mentor sans modération et éclaircir un modèle d'élection (éventuellement).
- L'exécutif sera à la charge des administrateurs (ou modérateur).

Néanmoins pas de réel changement quant au circuit des décisions prises pour le moment (échanges dans un salon privé avec les mentors). Si Discord proposait des rôles invisibles alors Administrateurs/modérateurs ne seraient pas visibles pour moi.

2020-09-03 20:30 UTC, Purexo commented
Bon, ça avance pas beaucoup cette histoire xD.

Pour synthétiser un peu tout ça, l'idée qui pourrait faire consensus est :
1. Création d'un rôle d'administrateur (pas besoin d'un rôle intermédiaire de modérateur a réévaluer avec l'évolution s de la communauté)
2. Nommage de ces administrateurs bon on va pas ce le cacher si personne ne s'y oppose ce sera les fondateurs actuels + @targos et @RomainLanz puisque ce sont les mentors les plus impliqué dans la communauté et qu'on (les fondateurs) a totalement confiance en eux pour ce rôles.
3. Suppression du rôle de modération pour les Mentors et réfléchir à ouvrir un peu plus les valves, un peu de sang neuf fera du bien je pense. On recentre le rôle autour de la bienveillance / enseignement et surtout animation de la communauté et incitation à la participation démocratique de la communauté.

Ça va à tout le monde ?

@Xstoudi tu va pouvoir reformuler tout ça ?

2020-09-23 10:57 UTC, Xstoudi commented
Pour moi c'est tout bon, je fais la modif en fin d'après-midi.
J'ai un peu de mal à saisir ce que vous préférez concernant le rôle des mentors.
La PR explicite le fait que les administrateurs appliquent les sanctions décidées par les mentors. Ca me paraît un peu lourd de passer par ce process dans certains cas (que nous n'avons pas nécessairement connu pour l'instant), qu'en pensez-vous ?

2020-09-23 11:17 UTC, Xstoudi commented
Batterie low, je termine en fin d'aprèm.

2020-09-24 20:55 UTC, Purexo requested changes
Cette fois ci jái utilisé la feature de proposition de changement correctement ^^

2020-09-24 20:55 UTC, Purexo commented on MODS.md
> +Un mentor ou un administrateur sera donc en droit de lever un avertissement **amical** envers le membre concerné par l'infraction.
```suggestion
Un administrateur sera donc en droit de lever un avertissement **amical** envers le membre concerné par l'infraction.
```

2020-09-24 20:55 UTC, Purexo commented on MODS.md
> +Un mentor ou un administrateur sera donc en droit de lever un avertissement envers le membre concerné par l'infraction. **(par message privé, si possible)**
```suggestion
Un administrateur sera donc en droit de lever un avertissement envers le membre concerné par l'infraction. **(par message privé, si possible)**
```

2020-09-24 20:55 UTC, Purexo commented on MODS.md
> +La **mise à pied** correspond à la rétrogradation du rôle du membre visé pendant une période fixe définie par le mentor ou l'administrateur.
```suggestion
La **mise à pied** correspond à la rétrogradation du rôle du membre visé pendant une période fixe définie par l'administrateur.
```

2020-09-24 20:55 UTC, Purexo commented on README.md
> +- Antoine
```suggestion
- Fraxken
- Xavier
- Purexo
- Tiyo
- Antoine
- Romain Lanz
- Targos
```

Nolan a choisis de ne plus être Mentor, mais nous restons des Mentors (les futurs Administrateurs)

2020-09-24 20:55 UTC, Purexo commented on MODS.md
> +Un mentor ou un administrateur sera donc en droit de lever un avertissement **amical** envers le membre concerné par l'infraction.
Petit rappel : pas de modération pour les Mentors

2020-09-24 20:59 UTC, Xstoudi commented
LGTM

2020-09-24 21:07 UTC, fraxken approved these changes

2020-09-24 21:33 UTC, Purexo approved these changes

2020-09-25 07:06 UTC, targos requested changes

2020-09-25 07:06 UTC, targos commented on MODS.md
> +Les administrateur établissent une sanction qui leur semble justifiée.
```suggestion
Les administrateurs établissent une sanction qui leur semble justifiée.
```

2020-09-25 07:06 UTC, targos commented on CONTRIBUTING.md
> +- Les administrateurs et mentors de la communauté ont le droit de création et modification des salons publiques dans les catégories `Autres` et `Évènements`.
```suggestion
- Les administrateurs et mentors de la communauté ont le droit de création et modification des salons publics dans les catégories `Autres` et `Évènements`.
```

2020-09-25 07:06 UTC, targos commented on README.md
> +Les administrateurs mettent en application les décisions prisent par la communauté et avertissent ou sanctionnent en cas de manquement au code de conduite de la part d'un membre.
```suggestion
Les administrateurs mettent en application les décisions prises par la communauté et avertissent ou sanctionnent en cas de manquement au code de conduite de la part d'un membre.
```

2020-09-25 07:06 UTC, targos commented on README.md
> +Ils sont nommés à la discrétion des fondateurs, triés parmis les mentors.
```suggestion
Ils sont nommés à la discrétion des fondateurs, triés parmi les mentors.
```

2020-09-25 07:06 UTC, targos commented on README.md
> +Tout comportement abusif peut être rapporté aux Mentors de la communauté. Vous pouvez les mentionner sur Discord avec `@Administrateurs`.
```suggestion
Tout comportement abusif peut être rapporté aux Administrateurs de la communauté. Vous pouvez les mentionner sur Discord avec `@Administrateurs`.
```

2020-09-25 07:06 UTC, targos commented on README.md
> +Les mentors sont des membres brillants par leur investissement dans la communauté en étant particulièrement actifs avec une communication adéquate, pédagogique et bienveillante.
```suggestion
Les mentors sont des membres brillant par leur investissement dans la communauté en étant particulièrement actifs avec une communication adéquate, pédagogique et bienveillante.
```

2020-09-25 07:06 UTC, targos commented on README.md
> +Ils sont nommés selon les modalités du ![Code de contribution](CONTRIBUTING.md).
```suggestion
Ils sont nommés selon les modalités du [Code de contribution](CONTRIBUTING.md).
```

Le point d'exclamation est pour afficher une image

2020-09-25 07:06 UTC, targos commented on README.md
> +- Tiyo
```suggestion
```

2020-09-25 08:09 UTC, RomainLanz approved these changes

2020-09-25 09:03 UTC, targos approved these changes

2020-09-25 09:24 UTC, fraxken approved these changes

2020-09-25 10:53 UTC, antoineneff commented on README.md
>  - Antoine
```suggestion

```

2020-09-25 11:35 UTC, antoineneff approved these changes

2020-10-04 16:21 UTC, merged